// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4tpD0cGbAZcG2pQJ-yurNd2yEIvAd5k8',
    appId: '1:793830090159:web:f295d2fdf6b51f59cbbb5a',
    messagingSenderId: '793830090159',
    projectId: 'musiqati-b0284',
    authDomain: 'musiqati-b0284.firebaseapp.com',
    storageBucket: 'musiqati-b0284.firebasestorage.app',
    measurementId: 'G-HPBSHLJMG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qrSJDL3IVQ4fbxhhU2YLsLrp-ld_eEQ',
    appId: '1:793830090159:android:4cb68e0e07b16907cbbb5a',
    messagingSenderId: '793830090159',
    projectId: 'musiqati-b0284',
    storageBucket: 'musiqati-b0284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Qs_FVmI_lEG1-jCtTlBv95ajl7wMbho',
    appId: '1:793830090159:ios:62d3f5ddeb41448dcbbb5a',
    messagingSenderId: '793830090159',
    projectId: 'musiqati-b0284',
    storageBucket: 'musiqati-b0284.firebasestorage.app',
    iosBundleId: 'com.musiqati.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4tpD0cGbAZcG2pQJ-yurNd2yEIvAd5k8',
    appId: '1:793830090159:web:d30c6b7291983a00cbbb5a',
    messagingSenderId: '793830090159',
    projectId: 'musiqati-b0284',
    authDomain: 'musiqati-b0284.firebaseapp.com',
    storageBucket: 'musiqati-b0284.firebasestorage.app',
    measurementId: 'G-F1SBJ7ZYW0',
  );
}
